### ISSUE TITLE
Yelp Api sometimes returns incomplete number of businesses

### ISSUE THREAD

**Issue by jplipata** [Yelp/yelp-api#162] opened 2016-08-11 04:06 UTC
I'm making Search API calls using the `offset` parameter.  Occasionally the API returns fewer actual results than specified in the `total` field in the response body.

E.g. The response body `total` field = 136, however when I make the last call with offset 120, I only receive 15 results, which totals 135 not 136

I don't believe the problem is with my code because, a) before today I never had this issue and I've made no changes to the code, and b) as a test I changed my query to search for a different `term` and the API returned the correct number of results and my code executed fine.

One note:  It doesn't seem like it should be related, but I reset my API keys today

Thanks

**Comment by tenprint** [comment] 2016-08-11 04:14
Here are the calls:
`https://api.yelp.com/v2/search?term=lunch&ll=40.7224164,-73.8428712,29.238&radius_filter=1000&offset=120` <-- This one has `total`=136 but only returns 135 results

`https://api.yelp.com/v2/search?term=restaurants&ll=40.7224164,-73.8428712,29.2&radius_filter=1000&offset=120` <-- This one has `total` = 140 and returns 140 results

**Comment by tenprint** [comment] 2016-08-12 21:24
bump

**Comment by kthouz** [comment] 2016-08-15 15:52
Am not sure if this might be the issue but have you thought about the index offset? Depending on the language you are using, sometimes the first index starts on 0 (Python, Java) or 1 (R, Matlab)

**Comment by tenprint** [comment] 2016-08-15 16:26
Thanks for the suggestion.

I have traced through my code and while it's possible there's something I'm overlooking, I do believe the API is returning an incorrect number of results at times.  E.g. For a query that has `total` of 140 and `offset` of 120, I should receive 20 results, however sometimes I receive less.  It's intermittent, sometimes it happens, sometimes it doesn't.

I'm making multiple calls in parallel to fetch all results, which is why the discrepancy causes problems.  E.g. you could argue that I could just calculate the `offset` based on the number of Businesses received, however I'm making the calls in parallel asynchronously, so my offsets are determined and the API calls are made before actual results are received.  

I have modified my code to handle this behavior so my app is now stable, but it would be nice to know what was going on.

**Comment by kthouz** [comment] 2016-08-15 16:59
Very Interesting! I just came across a similar issue on [stackoverflow](http://stackoverflow.com/questions/26918429/using-yelp-api-to-estimate-number-of-businesses-in-a-given-city). It looks like the total attributes gives different results. My guess is that this is just an internal glitch on how the api was built. Sure, it would be better to hear from Yelp Tech Support

**Comment by FYJen** [comment] 2016-08-16 21:42
Hi @tenprint :

We are able to reproduce using the same queries that you have provided but have yet to identify what the bug is so we do not have an ETA yet. We'll keep you posted if we find anything

**Comment by tenprint** [comment] 2016-08-18 02:30
Hi, below is some more info (responses/queries).  I'm getting inconsistent results using offsets -- `total` fluctuates depending on the response and I'm not always getting 20 businesses when I should.

I don't see why it would be related, but this started happening the day I reset my API key. 

Thanks

Responses:
{...}
offset=40 `total = 140` `businesses` size = 20
offset=60 `total = 140` `businesses` size = 20
offset=80 **`total = 149` `businesses` size = 18**
offset=100 `total = 140` `businesses` size = 20
offset=120 **`total = 149` `businesses` size = 17**

Calls:
https://api.yelp.com/v2/search?term=restaurants&ll=40.7222304,-73.8430018,20.0&radius_filter=1000 

https://api.yelp.com/v2/search?term=restaurants&ll=40.7222304,-73.8430018,20.0&radius_filter=1000&offset=20 

https://api.yelp.com/v2/search?term=restaurants&ll=40.7222304,-73.8430018,20.0&radius_filter=1000&offset=40

https://api.yelp.com/v2/search?term=restaurants&ll=40.7222304,-73.8430018,20.0&radius_filter=1000&offset=60

https://api.yelp.com/v2/search?term=restaurants&ll=40.7222304,-73.8430018,20.0&radius_filter=1000&offset=80 

https://api.yelp.com/v2/search?term=restaurants&ll=40.7222304,-73.8430018,20.0&radius_filter=1000&offset=100 

https://api.yelp.com/v2/search?term=restaurants&ll=40.7222304,-73.8430018,20.0&radius_filter=1000&offset=120

**Comment by tenprint** [comment] 2016-08-18 14:52
Here's another example using a different query:

https://api.yelp.com/v2/search?term=restaurants&ll=40.7430911,-73.988696,500.0&radius_filter=1000&offset=780

Response returned 19 businesses while `total` is 1175

https://api.yelp.com/v2/search?term=restaurants&ll=40.7430911,-73.988696,500.0&radius_filter=1000&offset=840

Response returned 18 businesses while `total` is 1175

https://api.yelp.com/v2/search?term=restaurants&ll=40.7430911,-73.988696,500.0&radius_filter=1000&offset=960

Returns 12 businesses and `total` = 1117

https://api.yelp.com/v2/search?term=restaurants&ll=40.7430911,-73.988696,500.0&radius_filter=1000&offset=980

Returns 20 businesses with `total` = 1053

**Comment by dan98765** [comment] 2018-07-18 02:02
We are in the process of archiving this API v2 github repository, and as part of that are closing out all issues. 

---
Announcement:
As of June 30, 2018, the API v2 has been discontinued and v2 endpoints no longer work. It has been replaced by [Yelp's Fusion API](https://www.yelp.com/fusion). This github repository is archived. There is a new Yelp Fusion-specific github repository at https://github.com/Yelp/yelp-fusion.

**Closed by dan98765** 2018-07-18 02:02 UTC
