### ISSUE TITLE
INVALID_SIGNATURE?

### ISSUE THREAD

**Issue by woohooyayaya** [Yelp/yelp-api#117] opened 2016-03-08 23:42 UTC
> https://api.yelp.com/v2/search/?limit=3&location=San%20Francisco%2C%20CA&oauth_consumer_key=tC6J9T0YPuJNcGV2kMv_1A&oauth_nonce=368da53e1dbf006caac773da5d01e6d7&oauth_signature=rV8oCbk%2BAj0Au9ucRcLgDxDE0Gg%3D&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1457479940&oauth_token=v3Co_EwQ6D99ruSBU6LWGieJFkaBB2HI&oauth_version=1.0&term=dinner https://api.yelp.com/v2/business/marlowe-san-francisco-2?oauth_consumer_key=tC6J9T0YPuJNcGV2kMv_1A&oauth_nonce=7e6555a569adb2966267a584edfddefb&oauth_signature=y0%2BjBnzp%2BqO9APwNHC2wiSrPYB8%3D&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1457479941&oauth_token=v3Co_EwQ6D99ruSBU6LWGieJFkaBB2HI&oauth_version=1.0 https://api.yelp.com/v2/business/hopwater-distribution-san-francisco?oauth_consumer_key=tC6J9T0YPuJNcGV2kMv_1A&oauth_nonce=aa1ca99c20c61d610c48273121616ba6&oauth_signature=Kqb1uPAy%2B2VB1kqIgDRu3Ln64LQ%3D&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1457479941&oauth_token=v3Co_EwQ6D99ruSBU6LWGieJFkaBB2HI&oauth_version=1.0 
> https://api.yelp.com/v2/business/la-fusi贸n-san-francisco-2?oauth_consumer_key=tC6J9T0YPuJNcGV2kMv_1A&oauth_nonce=74cf285c07482cfdfb67b7efaf053194&oauth_signature=aoNhh%2BJHaSJIEazTObp%2FCc%2Fqfh8%3D&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1457479942&oauth_token=v3Co_EwQ6D99ruSBU6LWGieJFkaBB2HI&oauth_version=1.0 
> Fatal error: Curl failed with error #400: {"error": {"text": "Signature was invalid", "id": "INVALID_SIGNATURE", "description": "Invalid signature. Expected signature base string: GET\u0026https%3A%2F%2Fapi.yelp.com%2Fv2%2Fbusiness%2Fla-fusi%25C3%25B3n-san-francisco-2\u0026oauth_consumer_key%3DtC6J9T0YPuJNcGV2kMv_1A%26oauth_nonce%3D74cf285c07482cfdfb67b7efaf053194%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1457479942%26oauth_token%3Dv3Co_EwQ6D99ruSBU6LWGieJFkaBB2HI%26oauth_version%3D1.0"}} in /home/foodiepal/public_html/api.php on line 98

I was following the example written in php. But I came across this problem when I was trying to traverse and get business by business ids. The first 2 businesses traversed fine. But the third one is always giving me 'INVALID SIGNATURE' error. I just searched normally in yelp and found out the business id is la-fusión-san-francisco-2 instead of la-fusi贸n-san-francisco-2. I'm not so sure if this is the case tho. 

Can anyone look into this for a bit? Thanks.

**Comment by butterfield** [comment] 2016-03-09 21:32
Hi there, I double checked and la-fusión-san-francisco-2 is the correct business id. (It corresponds to this business details page https://www.yelp.com/biz/la-fusi%C3%B3n-san-francisco-2 .)

I was able to reproduce the error. This looks like a bug in how the php sample handles business ids with unicode. I filed an issue here https://github.com/Yelp/yelp-api/issues/118

**Comment by watterso** [comment] 2016-03-09 21:36
Followup work will happen in #118, closing this issue.

**Closed by watterso** 2016-03-09 21:36 UTC
