### ISSUE TITLE
the node js API library returns "One or more parameter is missing: oauth_consumer_key"

### ISSUE THREAD

**Issue by franklingu** [Yelp/yelp-api#58] opened 2015-06-28 06:29 UTC
as title

**Comment by mittonk** [comment] 2015-06-28 23:03
Hm, I remember this working last time I ran it.

@franklingu : Have you already filled in your own `oauth_consumer_key` value into the example script?

**Comment by franklingu** [comment] 2015-06-29 01:32
Yes, the default node oauth actually puts those info in header but I think
yelp requires them as parameter in url




Gu Junchao
Major in Computer Engineering, National University of Singapore
Primary Email: *franklingujunchao@gmail.com <franklingujunchao@gmail.com>*
NUS Email: *A0105750@ <A0105750@nus.edu.sg>u.nus.edu <http://u.nus.edu>*

**Comment by mittonk** [comment] 2015-06-29 07:25
OK, looks like the Node.js example is actually part of a separate repo, https://github.com/olalonde/node-yelp .  Poking.

**Comment by franklingu** [comment] 2015-06-29 15:20
well, that is actually reported by me too ;P

**Comment by mittonk** [comment] 2015-07-02 17:51
@franklingu : That's a pretty snazzy blog post.

Debugging over in https://github.com/olalonde/node-yelp/issues/8 , closing this as a duplicate.

**Comment by mittonk** [comment] 2015-07-02 17:52
Duplicate of https://github.com/olalonde/node-yelp/issues/8 , debugging over there.

**Closed by mittonk** 2015-07-02 17:52 UTC
