### ISSUE TITLE
Can't we get accurate result response same as Yelp application provide?

### ISSUE THREAD

**Issue by supportkaira** [Yelp/yelp-api#157] opened 2016-07-25 10:06 UTC
We are using Yelp API  as business search API. It seems we are getting too much result which are not related Search Criteria. For  example, 

1. We are searching 'Walmart' keyword near "Agora Hills, CA"  using Yelp mobile application then we are getting accurate 2 result in that area. But when we use yelp API and do same search, we are getting so many other result  which are really not relevant and also not needed. Please suggest.

**Comment by mittonk** [comment] 2016-07-25 17:17
@supportkaira : Could you provide one of your responses from the API?  Having some concrete problem businesses will help the investigation.

**Comment by mittonk** [comment] 2016-07-25 17:28
@supportkaira : Hm, I see the same 20+ businesses when using the API or my phone app --- mostly Walmarts, some Targets; mostly Agoura Hills or Simi Valley.

Perhaps also include a screenshot of the phone that's only showing 2 results?  I suspect there's an extra filter or search radius set there.

**Comment by MarkXMx** [comment] 2016-08-02 03:54
Same problem: 
For instance, form the YELP API Console run a search:
https://api.yelp.com/v2/search/?term=3 FORTY GRILL&location=340 SINATRA DRIVE, HOBOKEN, NJ
you get 30 business, no one is even close to the one provided in the search. 
Whereas, this is the business: https://www.yelp.com/biz/3-forty-grill-hoboken
Is not returned in the 30 results.
How is it possible?

**Comment by mittonk** [comment] 2016-08-02 13:39
@MarkXMx : I think you're seeing a different issue.

https://www.yelp.com/biz/3-forty-grill-hoboken is marked "Closed".  The web page has the banner "Yelpers report this location has closed." and it's been closed long enough (looks like ~1.5 years) that it doesn't appear in www.yelp.com searches either.

**Comment by mittonk** [comment] 2016-09-16 19:49
Can't reproduce issue, closing.

**Closed by mittonk** 2016-09-16 19:49 UTC
